name = "gpsc-dental-bot"
main = "src/index.js"
compatibility_date = "2024-12-01"
node_compat = true

[vars]
BOT_NAME = "GPSC Dental Pulse 18"

[[d1_databases]]
binding = "DB"
database_name = "gpsc_dental_db"
database_id = "5d374e7d-2d0f-4c7e-87ae-aa2e2f949515"
